default: &default
  vCenterName: 'HOSTNAME'
  vCenterUser: 'Administrator'
  vCenterPass: 'PASS'
  sshConAddr: 'TEMPLATEIP'
  sshConUser: 'root'
  sshConPass: 'PASS'
 
development:
  <<: *default
 
test:
  <<: *default
 
production:
  <<: *default
