require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IpaddrsController do

  # This should return the minimal set of attributes required to create a valid
  # Ipaddr. As you add validations to Ipaddr, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ipaddress" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IpaddrsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ipaddrs as @ipaddrs" do
      ipaddr = Ipaddr.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ipaddrs).should eq([ipaddr])
    end
  end

  describe "GET show" do
    it "assigns the requested ipaddr as @ipaddr" do
      ipaddr = Ipaddr.create! valid_attributes
      get :show, {:id => ipaddr.to_param}, valid_session
      assigns(:ipaddr).should eq(ipaddr)
    end
  end

  describe "GET new" do
    it "assigns a new ipaddr as @ipaddr" do
      get :new, {}, valid_session
      assigns(:ipaddr).should be_a_new(Ipaddr)
    end
  end

  describe "GET edit" do
    it "assigns the requested ipaddr as @ipaddr" do
      ipaddr = Ipaddr.create! valid_attributes
      get :edit, {:id => ipaddr.to_param}, valid_session
      assigns(:ipaddr).should eq(ipaddr)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ipaddr" do
        expect {
          post :create, {:ipaddr => valid_attributes}, valid_session
        }.to change(Ipaddr, :count).by(1)
      end

      it "assigns a newly created ipaddr as @ipaddr" do
        post :create, {:ipaddr => valid_attributes}, valid_session
        assigns(:ipaddr).should be_a(Ipaddr)
        assigns(:ipaddr).should be_persisted
      end

      it "redirects to the created ipaddr" do
        post :create, {:ipaddr => valid_attributes}, valid_session
        response.should redirect_to(Ipaddr.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ipaddr as @ipaddr" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ipaddr.any_instance.stub(:save).and_return(false)
        post :create, {:ipaddr => { "ipaddress" => "invalid value" }}, valid_session
        assigns(:ipaddr).should be_a_new(Ipaddr)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ipaddr.any_instance.stub(:save).and_return(false)
        post :create, {:ipaddr => { "ipaddress" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ipaddr" do
        ipaddr = Ipaddr.create! valid_attributes
        # Assuming there are no other ipaddrs in the database, this
        # specifies that the Ipaddr created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ipaddr.any_instance.should_receive(:update).with({ "ipaddress" => "MyString" })
        put :update, {:id => ipaddr.to_param, :ipaddr => { "ipaddress" => "MyString" }}, valid_session
      end

      it "assigns the requested ipaddr as @ipaddr" do
        ipaddr = Ipaddr.create! valid_attributes
        put :update, {:id => ipaddr.to_param, :ipaddr => valid_attributes}, valid_session
        assigns(:ipaddr).should eq(ipaddr)
      end

      it "redirects to the ipaddr" do
        ipaddr = Ipaddr.create! valid_attributes
        put :update, {:id => ipaddr.to_param, :ipaddr => valid_attributes}, valid_session
        response.should redirect_to(ipaddr)
      end
    end

    describe "with invalid params" do
      it "assigns the ipaddr as @ipaddr" do
        ipaddr = Ipaddr.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ipaddr.any_instance.stub(:save).and_return(false)
        put :update, {:id => ipaddr.to_param, :ipaddr => { "ipaddress" => "invalid value" }}, valid_session
        assigns(:ipaddr).should eq(ipaddr)
      end

      it "re-renders the 'edit' template" do
        ipaddr = Ipaddr.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ipaddr.any_instance.stub(:save).and_return(false)
        put :update, {:id => ipaddr.to_param, :ipaddr => { "ipaddress" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ipaddr" do
      ipaddr = Ipaddr.create! valid_attributes
      expect {
        delete :destroy, {:id => ipaddr.to_param}, valid_session
      }.to change(Ipaddr, :count).by(-1)
    end

    it "redirects to the ipaddrs list" do
      ipaddr = Ipaddr.create! valid_attributes
      delete :destroy, {:id => ipaddr.to_param}, valid_session
      response.should redirect_to(ipaddrs_url)
    end
  end

end
